//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetDictResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        Forms.ServiceReference.GetDictResponse GetDict(Forms.ServiceReference.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference.GetDictResponse> GetDictAsync(Forms.ServiceReference.GetDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetRecordResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecord", ReplyAction="*")]
        Forms.ServiceReference.GetRecordResponse GetRecord(Forms.ServiceReference.GetRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference.GetRecordResponse> GetRecordAsync(Forms.ServiceReference.GetRecordRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        Forms.ServiceReference.AddDictResponse AddDict(Forms.ServiceReference.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference.AddDictResponse> AddDictAsync(Forms.ServiceReference.AddDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        Forms.ServiceReference.UpdDictResponse UpdDict(Forms.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference.UpdDictResponse> UpdDictAsync(Forms.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Guid DelDict(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> DelDictAsync(System.Guid id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(Forms.ServiceReference.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(Forms.ServiceReference.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference.Contact[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(Forms.ServiceReference.Contact[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecord", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.GetRecordRequestBody Body;
        
        public GetRecordRequest() {
        }
        
        public GetRecordRequest(Forms.ServiceReference.GetRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public GetRecordRequestBody() {
        }
        
        public GetRecordRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.GetRecordResponseBody Body;
        
        public GetRecordResponse() {
        }
        
        public GetRecordResponse(Forms.ServiceReference.GetRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference.Contact GetRecordResult;
        
        public GetRecordResponseBody() {
        }
        
        public GetRecordResponseBody(Forms.ServiceReference.Contact GetRecordResult) {
            this.GetRecordResult = GetRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(Forms.ServiceReference.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(string name, string phone) {
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(Forms.ServiceReference.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference.Contact AddDictResult;
        
        public AddDictResponseBody() {
        }
        
        public AddDictResponseBody(Forms.ServiceReference.Contact AddDictResult) {
            this.AddDictResult = AddDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(Forms.ServiceReference.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phone;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(System.Guid id, string name, string phone) {
            this.id = id;
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(Forms.ServiceReference.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference.Contact UpdDictResult;
        
        public UpdDictResponseBody() {
        }
        
        public UpdDictResponseBody(Forms.ServiceReference.Contact UpdDictResult) {
            this.UpdDictResult = UpdDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Forms.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Forms.ServiceReference.WebServiceSoap>, Forms.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference.GetDictResponse Forms.ServiceReference.WebServiceSoap.GetDict(Forms.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public Forms.ServiceReference.Contact[] GetDict() {
            Forms.ServiceReference.GetDictRequest inValue = new Forms.ServiceReference.GetDictRequest();
            inValue.Body = new Forms.ServiceReference.GetDictRequestBody();
            Forms.ServiceReference.GetDictResponse retVal = ((Forms.ServiceReference.WebServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference.GetDictResponse> Forms.ServiceReference.WebServiceSoap.GetDictAsync(Forms.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference.GetDictResponse> GetDictAsync() {
            Forms.ServiceReference.GetDictRequest inValue = new Forms.ServiceReference.GetDictRequest();
            inValue.Body = new Forms.ServiceReference.GetDictRequestBody();
            return ((Forms.ServiceReference.WebServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference.GetRecordResponse Forms.ServiceReference.WebServiceSoap.GetRecord(Forms.ServiceReference.GetRecordRequest request) {
            return base.Channel.GetRecord(request);
        }
        
        public Forms.ServiceReference.Contact GetRecord(System.Guid id) {
            Forms.ServiceReference.GetRecordRequest inValue = new Forms.ServiceReference.GetRecordRequest();
            inValue.Body = new Forms.ServiceReference.GetRecordRequestBody();
            inValue.Body.id = id;
            Forms.ServiceReference.GetRecordResponse retVal = ((Forms.ServiceReference.WebServiceSoap)(this)).GetRecord(inValue);
            return retVal.Body.GetRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference.GetRecordResponse> Forms.ServiceReference.WebServiceSoap.GetRecordAsync(Forms.ServiceReference.GetRecordRequest request) {
            return base.Channel.GetRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference.GetRecordResponse> GetRecordAsync(System.Guid id) {
            Forms.ServiceReference.GetRecordRequest inValue = new Forms.ServiceReference.GetRecordRequest();
            inValue.Body = new Forms.ServiceReference.GetRecordRequestBody();
            inValue.Body.id = id;
            return ((Forms.ServiceReference.WebServiceSoap)(this)).GetRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference.AddDictResponse Forms.ServiceReference.WebServiceSoap.AddDict(Forms.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public Forms.ServiceReference.Contact AddDict(string name, string phone) {
            Forms.ServiceReference.AddDictRequest inValue = new Forms.ServiceReference.AddDictRequest();
            inValue.Body = new Forms.ServiceReference.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            Forms.ServiceReference.AddDictResponse retVal = ((Forms.ServiceReference.WebServiceSoap)(this)).AddDict(inValue);
            return retVal.Body.AddDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference.AddDictResponse> Forms.ServiceReference.WebServiceSoap.AddDictAsync(Forms.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference.AddDictResponse> AddDictAsync(string name, string phone) {
            Forms.ServiceReference.AddDictRequest inValue = new Forms.ServiceReference.AddDictRequest();
            inValue.Body = new Forms.ServiceReference.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((Forms.ServiceReference.WebServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference.UpdDictResponse Forms.ServiceReference.WebServiceSoap.UpdDict(Forms.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public Forms.ServiceReference.Contact UpdDict(System.Guid id, string name, string phone) {
            Forms.ServiceReference.UpdDictRequest inValue = new Forms.ServiceReference.UpdDictRequest();
            inValue.Body = new Forms.ServiceReference.UpdDictRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            Forms.ServiceReference.UpdDictResponse retVal = ((Forms.ServiceReference.WebServiceSoap)(this)).UpdDict(inValue);
            return retVal.Body.UpdDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference.UpdDictResponse> Forms.ServiceReference.WebServiceSoap.UpdDictAsync(Forms.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference.UpdDictResponse> UpdDictAsync(System.Guid id, string name, string phone) {
            Forms.ServiceReference.UpdDictRequest inValue = new Forms.ServiceReference.UpdDictRequest();
            inValue.Body = new Forms.ServiceReference.UpdDictRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((Forms.ServiceReference.WebServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        public System.Guid DelDict(System.Guid id) {
            return base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task<System.Guid> DelDictAsync(System.Guid id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
