//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 06.12.2021 10:00:19
namespace ConsoleApplication1.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for lab6Entities in the schema.
    /// </summary>
    public partial class lab6Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new lab6Entities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public lab6Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "lab6Model", "ConsoleApplication1.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ConsoleApplication1.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("lab6Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Note> Note
        {
            get
            {
                if ((this._Note == null))
                {
                    this._Note = base.CreateQuery<Note>("Note");
                }
                return this._Note;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Note> _Note;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Students> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Students>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Students> _Students;
        /// <summary>
        /// There are no comments for Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNote(Note note)
        {
            base.AddObject("Note", note);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStudents(Students students)
        {
            base.AddObject("Students", students);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"lab6Model\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Enti" +
                "tyType Name=\"Note\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=" +
                "\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"id_s\" Type=\"Edm.Int32\" /><Propert" +
                "y Name=\"subj\" Type=\"Edm.String\" MaxLength=\"25\" FixedLength=\"false\" Unicode=\"true" +
                "\" /><Property Name=\"note1\" Type=\"Edm.String\" MaxLength=\"25\" FixedLength=\"false\" " +
                "Unicode=\"true\" /><NavigationProperty Name=\"Students\" Relationship=\"lab6Model.FK_" +
                "_Note__id_s__267ABA7A\" ToRole=\"Students\" FromRole=\"Note\" /></EntityType><EntityT" +
                "ype Name=\"Students\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"name\" Type=\"Edm.String\" MaxLengt" +
                "h=\"20\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"Note\" Rela" +
                "tionship=\"lab6Model.FK__Note__id_s__267ABA7A\" ToRole=\"Note\" FromRole=\"Students\" " +
                "/></EntityType><Association Name=\"FK__Note__id_s__267ABA7A\"><End Type=\"lab6Model" +
                ".Students\" Role=\"Students\" Multiplicity=\"0..1\" /><End Type=\"lab6Model.Note\" Role" +
                "=\"Note\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Students\"><Pr" +
                "opertyRef Name=\"id\" /></Principal><Dependent Role=\"Note\"><PropertyRef Name=\"id_s" +
                "\" /></Dependent></ReferentialConstraint></Association></Schema><Schema Namespace" +
                "=\"Lab6\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Na" +
                "me=\"lab6Entities\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Note\" Entit" +
                "yType=\"lab6Model.Note\" /><EntitySet Name=\"Students\" EntityType=\"lab6Model.Studen" +
                "ts\" /><FunctionImport Name=\"ChangeNote\" ReturnType=\"Collection(lab6Model.Note)\" " +
                "EntitySet=\"Note\" m:HttpMethod=\"GET\"><Parameter Name=\"id\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Parameter Name=\"subject\" Type=\"Edm.String\" /><Parameter Name=\"Note" +
                "\" Type=\"Edm.Int32\" Nullable=\"false\" /><Parameter Name=\"studentId\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /></FunctionImport><FunctionImport Name=\"InsertNote\" ReturnT" +
                "ype=\"Collection(lab6Model.Note)\" EntitySet=\"Note\" m:HttpMethod=\"GET\"><Parameter " +
                "Name=\"subject\" Type=\"Edm.String\" /><Parameter Name=\"Note\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" /><Parameter Name=\"studentId\" Type=\"Edm.Int32\" Nullable=\"false\" /></" +
                "FunctionImport><FunctionImport Name=\"ChangeStudent\" ReturnType=\"Collection(lab6M" +
                "odel.Students)\" EntitySet=\"Students\" m:HttpMethod=\"GET\"><Parameter Name=\"id\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" /><Parameter Name=\"name\" Type=\"Edm.String\" /></Fu" +
                "nctionImport><FunctionImport Name=\"InsertStudent\" ReturnType=\"Collection(lab6Mod" +
                "el.Students)\" EntitySet=\"Students\" m:HttpMethod=\"GET\"><Parameter Name=\"name\" Typ" +
                "e=\"Edm.String\" /></FunctionImport><AssociationSet Name=\"FK__Note__id_s__267ABA7A" +
                "\" Association=\"lab6Model.FK__Note__id_s__267ABA7A\"><End Role=\"Note\" EntitySet=\"N" +
                "ote\" /><End Role=\"Students\" EntitySet=\"Students\" /></AssociationSet></EntityCont" +
                "ainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for lab6Model.Note in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Note")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Note : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Note CreateNote(int ID)
        {
            Note note = new Note();
            note.id = ID;
            return note;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property id_s in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> id_s
        {
            get
            {
                return this._id_s;
            }
            set
            {
                this.Onid_sChanging(value);
                this._id_s = value;
                this.Onid_sChanged();
                this.OnPropertyChanged("id_s");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _id_s;
        partial void Onid_sChanging(global::System.Nullable<int> value);
        partial void Onid_sChanged();
        /// <summary>
        /// There are no comments for Property subj in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string subj
        {
            get
            {
                return this._subj;
            }
            set
            {
                this.OnsubjChanging(value);
                this._subj = value;
                this.OnsubjChanged();
                this.OnPropertyChanged("subj");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _subj;
        partial void OnsubjChanging(string value);
        partial void OnsubjChanged();
        /// <summary>
        /// There are no comments for Property note1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string note1
        {
            get
            {
                return this._note1;
            }
            set
            {
                this.Onnote1Changing(value);
                this._note1 = value;
                this.Onnote1Changed();
                this.OnPropertyChanged("note1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _note1;
        partial void Onnote1Changing(string value);
        partial void Onnote1Changed();
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Students Students
        {
            get
            {
                return this._Students;
            }
            set
            {
                this._Students = value;
                this.OnPropertyChanged("Students");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Students _Students;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for lab6Model.Students in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Students")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Students : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Students object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Students CreateStudents(int ID)
        {
            Students students = new Students();
            students.id = ID;
            return students;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Note> Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this._Note = value;
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Note> _Note = new global::System.Data.Services.Client.DataServiceCollection<Note>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
