LOAD DATA
INFILE 'C:\lab18\data.txt'
DISCARDFILE 'C:\lab18\data.dis'
INTO TABLE LAB18
FIELDS TERMINATED BY ","
(
INTVALUE "round(:INTVALUE, 2)",
CHARVALUE "upper(:CHARVALUE)",
DATEVALUE date "YYYY-MM-DD"
)